---
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE}
# Knitr options
knitr::opts_chunk$set(
  cache = FALSE, 
  warning = FALSE, 
  message = FALSE, 
  dpi = 180, 
  fig.align = "center", 
  comment = "#>",
  fig.width = 8, 
  fig.height = 6
)

# Libs and deps
suppressPackageStartupMessages(library(tidyverse))
library(aws.s3)
library(aws.signature)
library(readr)
```

<center> <h2>1- CLANING METADATA</h2> </center>

### Set some vars

```{r}
bucket_name <- "s3://cihr-hiv-rv306"
raw_meta <- "vaginal/metadata/RV306_CVM_ShippingManifest_2022_SB_metadata.xlsx"
raw_lims <- "vaginal/data_transfer/metadata/RV306 CVM-2022-11-08_lims.xlsx"
```

### Reading and inspection clinical metadata

```{r}
meta <-
  aws.s3::s3read_using(
    xlsx::read.xlsx,
    object = raw_meta,
    bucket = bucket_name,
    sheetIndex = 1
  ) %>% tibble::as_tibble()

glimpse(meta)
```

### Reading and inspection technical metadata (lims)

```{r}
lims <-
  aws.s3::s3read_using(
    xlsx::read.xlsx,
    object = raw_lims,
    bucket = bucket_name,
    sheetIndex = 1
  ) %>% tibble::as_tibble()

glimpse(lims)
```


### Cleaning clinical metadata

```{r}
meta <-
  meta %>%
  dplyr::select(-NA.) %>% 
  dplyr::rename(
    Collection_date = Date_Collected,
    Study_number_visit = `Study.Number_Visit`,
    Treatment_group = `Treatemnt.Group`,
    Arm = `Active.Placebo`,
    Heme_test = `Heme.test`
  )

meta <- 
  meta %>%
  mutate(
    PatientID = str_c("p_", Study_Number),
    Visit_Week = case_when(
      Visit_Code %in% '4U1' ~ 'Wk 14',
      Visit_Code %in% '9U1' ~ 'Wk 50',
      T ~ Visit_Week
    ),
    Treatment_group = case_when(
      Study_number_visit %in% '1047_1' ~ 'no_boost',
      PatientID %in% '2006' ~ 'no_boost',
      TRUE ~ as.character (Treatment_group)
    ),
    Treatment_group = str_c("t_", Treatment_group),
    Receiving_Lab = str_replace_all(Receiving_Lab, "Padres", "Paredes"),
    Collection_date = str_replace_all(Collection_date, "-", "/"),
    Timepoint = str_replace_all(Visit_Week, "Wk ", "") %>% as.numeric(), 
    Medical_center = str_remove_all(Barcode_ID, "[:digit:].*")
  )
         
glimpse(meta)
```

### Cleaning technical metadata (lims)

```{r}
lims <-
  lims %>%
  dplyr::select(-NA., -NA..1) %>% 
  dplyr::mutate(
    Barcode_ID = sub("\\_.*", "\\", Sample.Name)
  ) %>% 
  dplyr::rename(
    Parent_Sample = `Parent.Sample`,
    SampleID = `Sample..Sample.ID`,
    Sample_name = `Sample.Name`,
    Plate_name = `Plate.Name`,
    Concentration_ng_ul = `Concentration..ng.ul.`
  ) 
```

### Merge clinical and lims metadata

```{r}
f_meta <-
  left_join(meta, lims, by = c("Barcode_ID"), multiple = "all") %>%
  dplyr::relocate(
    SampleID,
    Barcode_ID,
    PatientID,
    Timepoint,
    Collection_date,
    Visit_Code,
    Study_number_visit,
    Treatment_group,
    Arm,
    Heme_test,
    .before = 1
  )

glimpse(f_meta)

f_meta %>% data.table::data.table()
```

### Exporting to S3

```{r}
aws.s3::s3write_using(
  readr::write_csv,
  object = "vaginal/metadata/metadata.csv",
  x = f_meta,
  bucket = "s3://cihr-hiv-rv306"
)
```
